apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: istio
  secretName: istio-ca
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-ca
spec:
  ca:
    secretName: istio-ca
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ztunnel-root-certificate
  namespace: istio-system
data:
  ca.crt: $(kubectl get secret istio-ca -n cert-manager -o json | jq '.data["tls.crt"]' -r | base64 -d| jq -R --slurp)
